INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface Roxa',3,42.84,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cenoura Higienizada',3,17.42,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Dovyalis',3,63.07,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Não Especificadas',3,66.6,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Gengibre ',3,15.09,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Limão Taiti',3,73.47,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Poncã',3,53.34,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata-Baroa/Mandioquinha-Salsa',3,53.78,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Limão-Cravo',3,65.26,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Maracujá',5,3.89,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Mirtilo',5,64.5,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Caxi ',5,43.49,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Coentro ',5,65.72,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Espelta',5,38.19,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Margaridas',5,25.22,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Médio Pasteurizado Acidificado Com Ácido Cítrico',5,11.75,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface Mimosa',5,11.29,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vinho Tinto Seco Petite Syrah',7,51.28,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outras Mudas Não Especificadas',7,31.56,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Avelã E Cacau',7,37.89,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Lima',7,71.83,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Erva-Doce',7,55.58,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mostarda',7,19.88,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Repolho Roxo',7,50.95,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mamão Papaya',8,70.94,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Guaraná',8,18.25,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Arroz E Amêndoa',8,24.81,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cana De Açúcar',8,28.47,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mexirica Pokan',8,19.16,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Lichia',8,7.36,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sorbet De Açaí Com Guaraná E Açúcar Demerara Tipo 2',8,65.93,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Médio',8,58.05,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Limão Cravo',8,31.53,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão Vermelho',9,4.4,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ponkan',9,47.63,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Creme De Coco Para Cozinhar',9,18.49,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Médio',9,14.1,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Pêssego',9,52.26,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Guabiroba',9,69.7,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Castanha De Caju Assada A Seco',9,61.39,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Atemóia',9,43.98,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Avelã E Cacau',9,45.36,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abacaxi Ou Ananás',12,1.75,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ovo Integral Pasteurizado Congelado',12,65.4,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vagem Rasteira',12,48.9,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sapota',12,14.97,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata Doce',15,59.17,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Beldroega',15,29.15,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milheto',15,12.5,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Espelta',15,1.44,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('1- Hortaliças',15,17.25,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Panqueca De Shitake',15,2.53,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Beterraba Higienizada',15,65.73,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Tomate Estaqueado',15,32.64,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve Folha',15,31.25,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Fava',17,50.52,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Physalis',17,41.12,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Grão De Bico',17,25.7,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve Crespa',19,7.15,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abóbora Madura',19,17.96,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Brócolis Comum',19,59.16,0,'1KG')
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Da Terra',19,72.02,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Quebra Pedra ',19,2.33,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Chalota Em Conserva',19,38.75,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abobrinha Italiana',19,44.73,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho Em Salmoura',19,19.19,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sorbet De Açaí Com Guaraná E Açúcar Demerara Tipo 2',19,60.39,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Suco De Cana De Açúcar',20,23.11,0,'100ml')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cará-Moela/Ar',20,54.92,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Gergelim Preto',20,7.2,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milho  Verde Ou Doce Mesmo Em Espiga',20,32.27,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mudas De  Frutíferas De Lavoura Permanente',20,40.3,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Carqueja',20,64.81,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milho-Verde',20,7.43,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Laranja Poncã',20,15.67,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata-Baroa Ou Mandioquinha-Salsa',20,65.64,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Seleta',21,47.2,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outros Grãos Não Especificados',21,55.2,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mostarda ',21,27.18,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mamão Papaia',21,71.48,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Capim Limão/Cidró',21,42.07,0,'1CX c/ 12 Itens')
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abiu ',21,49.29,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mexirica',21,55.07,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ginseng',22,62.86,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sálvia Ou Salva',22,10.45,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Lírio Do Brejo',22,20.62,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Chicória-De-Folha-Crespa',22,28.86,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Aveia Com Cálcio',22,22.74,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Médio Acidificado Com Suco De Limão',22,65.85,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Castanha De Caju Assada A Seco',23,19.56,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Manga Ubá',23,38.39,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface Rocha',23,46.86,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Moringa',23,43.46,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Melância',23,47.81,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sapoti',23,63.39,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Chips De Inhame',23,11.29,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açúcar Cristal',23,24.75,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mostarda ',25,9.38,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ovo Com Sal Pasteurizado Resfriado',25,46.2,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Funcho',25,46.86,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Erva Mate',25,47.16,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Arroz',25,49.26,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pepino Japonês',25,35.1,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Manga Ubá',25,28.76,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata-Baroa/Mandioquinha-Salsa',25,18.96,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão Carioca',26,37.72,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Arroz E Amêndoa',26,8.12,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abobrinha',26,24.47,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijao Carioca',26,52.86,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vagem Rasteira',26,63.29,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Manjerona',26,31.83,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Laranja Lima',26,8.52,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pimentão Vermelho',27,58.64,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Gengibre',27,36.29,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pimentão Amarelo',27,26.27,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão Preto',27,52.43,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve-Flor',27,38.91,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Almeirao',27,37.74,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Noz Moscada',27,12.02,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outras Hortaliças Não Especificadas',27,4.67,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açúcar Cristal',28,47.93,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ponkan',28,8.31,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Taioba ',28,55.12,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Trigo',28,16.73,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Crotalária',28,40.98,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mistura De Ovos Desidratada',28,40.73,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Franboesa Congelada',28,43.09,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cheiro Verde',28,48.3,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milho  Verde Ou Doce Mesmo Em Espiga',28,63.41,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijao Fradinho',28,63.46,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mudas De Hortaliças',29,57.29,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sucupira',29,44.84,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milho Verde ',29,54.53,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão-Guandu',32,40.2,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Repolho Branco',32,24.85,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vinho Tinto Seco Tempranillo',32,57.38,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Aveia Com Chocolate',32,44.7,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pimentão Mini',33,38.73,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Milheto',36,20.01,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Caruru',36,73.07,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Laranja',38,74.45,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Favela',38,58.45,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ovo Com Sal Pasteurizado Resfriado',38,56.06,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Poejo',38,63.9,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outras Hort Folhosas Não Especificadas',38,74.68,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve-Crespa Ou Couve-Manteiga',39,68.95,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aveia',39,17.96,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Castanha De Caju Assada A Seco',39,74.49,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Castanha De Caju',40,43.38,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve-Crespa Ou Couve-Manteiga',40,69.59,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface',40,23.3,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Maná',40,1.06,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outras Frutas Não Especificas',40,45.38,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mamão',40,48.72,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Graviola',40,43.04,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Arruda ',40,23.02,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outros Grãos Não Especificados',40,34.94,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Creme De Abóbora Com Castanha De Caju',41,39.5,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Melancia',41,48.08,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sálvia Ou Salva',41,19.8,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vinagre De Vinho Tinto',41,45.56,0,'1CX c/ 12 Itens 5L')
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mangostão',41,15.32,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Funcho ',41,49.07,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Arroz',41,72.35,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Broa',41,5.68,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sopa Creme De Legumes',42,67.26,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pitanga',42,60.21,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aipim/Mandioca Descascada',42,12.62,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Soja',42,24.21,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Nêspera',42,66.09,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abacaxi',43,67.02,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata-Baroa/Mandioquinha-Salsa',43,62.74,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Amora Congelada',43,13.85,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cenora',43,20.24,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ora Pro Nobis',43,33.67,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Etc',44,24.37,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Café',44,60.84,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata Inglesa',44,67.88,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pimenta Rosa ',44,22.74,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Camomila',44,16.76,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abacate',44,10.57,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cisal',44,42.64,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mangerona ',44,61.74,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Especial Acidificado Com Ácido Cítrico',44,61.05,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Polpa De Tomate',44,47.0,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Calêndula',45,39.98,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho Porró',45,13.05,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cenoura Higienizada',45,47.52,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Farinha De Mandioca',45,41.32,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cevada',45,20.24,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aipim/Mandioca Congelado',45,74.77,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Hibisco',45,41.93,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho Porró',46,69.62,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Goiaba',46,56.28,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface Romana',46,59.66,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cultivo De Beterraba',46,41.65,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Taioba/Taia',46,61.39,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cebolete',46,58.02,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Caruru',46,39.79,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mistura De Ovos Desidratada',46,73.85,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Amora Branca',46,67.52,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Manga Rosa',47,14.47,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida Mista De Fruta Adoçada',47,17.37,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mandioquinha -Salsa',47,24.78,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho Pequi',47,73.93,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cacau',47,66.38,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Chips De Inhame',47,2.6,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Quibe Vegano De Quinoa Com Abóbora E Legumes No Vapor',47,8.94,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pêssego',47,51.41,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Seriguela',47,72.78,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Jambu ',49,3.69,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Jenipapo',49,67.56,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abobora Comum',49,5.25,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Funcho',50,33.05,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mandioca Amarela',50,20.55,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mudas De Hortaliças',50,50.07,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Araçá',51,22.13,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mix De Frutas Congeladas',51,33.96,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Iscas De Carne Com Purê De Abóbora E Couve',51,72.14,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Uvaia',51,70.1,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Guabiroba',52,13.79,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Rabanete',52,14.61,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Lichia',52,37.92,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Arroz Com Cálcio',52,68.26,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outras Frutas Não Especificas',52,37.72,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pitaia',52,48.37,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve Folha',52,26.49,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Gardenia',52,45.82,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Noz Pecã',52,52.32,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aveia',53,44.44,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pães',53,28.49,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Jerimum',53,5.67,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Menta',53,54.34,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açafrão Da Terra',53,21.29,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Frutas Vermelhas',53,12.58,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ovo Com Sal Hidrolisado Pasteurizado Resfriado',53,41.69,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão Verde',53,49.41,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mandioquinha -Salsa',53,2.41,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abóbora',53,37.44,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abricó',54,42.43,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Noni',54,50.78,0,'10CX')
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Café Arábica E Mexerica Ponkan',54,56.65,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Jambo ',54,25.04,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mamão Formosa',54,28.64,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açafrão',54,22.67,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Rambutã',54,55.28,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Tangerina',54,29.73,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Clara De Ovo Pasteurizada Desidratada',54,15.77,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aspargo',55,41.68,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Outras Hortaliças Não Especificadas',55,37.76,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Sapoti',55,17.58,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Losna Ou Absinto',55,42.55,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Salsinha',55,24.83,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Goiaba',55,43.69,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Lasanha De Berinjela Ao Sugo',56,52.83,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Nhoque De Mandioquinha',57,59.98,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pinchão',58,37.79,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Doce De Araçá',58,17.39,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Manga Em Pó',58,17.44,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mamão Papaya',58,30.25,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Endro',59,44.6,0,'1UN')
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aipim Ou Macaxeira ',59,42.19,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mistura De Ovos Desidratada',59,36.25,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Coentro Desidratado',60,17.77,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Arroz E Quinoa',60,65.82,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aipim/Mandioca Congelado',61,14.97,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Capuchinha',61,68.0,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Acerola Em Pó',61,5.52,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Urucum ',61,61.18,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Dente De Leão',61,12.28,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Geleia De Frutas Vermelhas',62,28.29,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milho  Verde Ou Doce Mesmo Em Espiga',62,24.43,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface Americana',62,50.73,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bardana ',63,52.85,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão-De-Porco',63,7.44,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Hortelã',63,72.5,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Quebra Pedra ',63,47.96,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Chicória-De-Folha-Lisa',63,57.16,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Café Torrado Em Grão',64,69.02,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Chuchu Higienizado',64,65.04,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pulmonária',64,15.96,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Goiaba Branca',64,62.97,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho Pequi',64,8.4,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Noz Pecã',64,19.78,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cana-De-Açúcar',64,65.65,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Panqueca De Espinafre E Ricota',64,35.05,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mandioca',65,56.44,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alecrim ',65,7.41,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Anis Doce',66,62.05,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve',66,7.9,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Gema De Ovo Pasteurizada Desidratada',66,16.11,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bolos',67,54.01,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Coco',67,64.45,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Tomate Rasteiro',67,30.48,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Eucalipto',67,46.82,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Espinafres ',67,50.07,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Tâmara',68,60.73,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vagem Rasteira',70,52.1,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Taioba ',70,4.66,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Creme De Aveia Para Cozinhar',70,58.79,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Nhoque De Batata Doce Ao Sugo',70,70.11,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alfavaca Anis',70,56.07,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Doce De Goiaba',70,1.52,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Médio Ou Regular',70,29.38,0,'1KG')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mudas De Hortaliças',71,49.51,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mudas ',71,73.33,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alface Lisa',71,50.77,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Catalonha',71,44.66,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alfazema',71,20.2,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho',71,16.66,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vagem Rasteira',71,69.89,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Jabuticaba',71,12.65,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bolos',72,33.94,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Suco De Uva Tinto Integral',72,55.79,0,'1CX c/ 6 Itens 1L')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Erva-Doce Ou Anis Verde ',72,8.52,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Batata Baroa',72,24.24,0,'1CX c/ 3 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Repolho Roxo',73,7.26,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Lima',73,61.22,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Capim Limão ',73,6.53,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ponkan',73,36.54,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Mamão',73,24.25,0,'10CX')
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Especial Pasteurizado Acidificado Com Ácido Cítrico',73,71.41,0,'1CX c/ 12 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Abobrinha',74,12.59,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Camomila ',74,18.8,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Bebida De Aveia Com Chocolate',74,54.64,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Ora Pro Nobis',74,42.55,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Grão De Bico',75,45.43,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Alho-Poró',75,15.7,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Feijão Preto E Feijão Vermelho',75,8.17,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Pequi',75,66.03,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Graviola',75,23.45,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Café Em Grão',76,39.11,0,'1UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Brócolis Ramoso',76,28.84,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cajá',76,36.2,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Hibisco',76,68.79,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Caruru',76,45.9,0,'100g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Açaí Especial Acidificado Com Ácido Cítrico',76,48.18,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Panqueca De Espinafre E Ricota',76,33.07,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Milho Verde',76,5.27,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aveia Em Grãos',76,1.48,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Fruta Do Conde',77,9.99,0,NULL)
GO

INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Gervão Roxo ',77,40.61,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Amora Preta',77,32.58,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cupuaçu Em Pó',77,57.95,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Beldroega',77,53.24,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Vinagre Balsâmico Modena',77,55.56,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Peixinho',77,72.92,0,'10UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Cenoura Higienizada',77,69.5,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Café Torrado Em Grão',77,19.35,0,'3UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Rúcula Ou Pinchão',78,26.1,0,'10g')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Aipim/Mandioca Congelado',78,33.68,0,'10CX')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Farinha De Banana Verde',78,73.39,0,'6UN')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Endro',79,70.72,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Capim Santo',79,45.85,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Jatobá',79,8.92,0,NULL)
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Da Pérsia',79,30.93,0,'1CX c/ 6 Itens')
INSERT INTO PRODUCT (ProductName,SupplierId,UnitPrice,IsDiscontinued,PackageName) VALUES ('Couve-Manteiga',79,14.43,0,NULL)
GO
